name: check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'liberica'
#          cache: 'gradle'
      - name: gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
