name: Check build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'liberica'
#          cache: 'gradle'
      - name: Run gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
